=== NicoButter/ldp_tp2_2025/EJERCICIO_02/BUTTERFIELD_TP02_E02_GENEROS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Ejercicio de la materia "Laboratorio de Programación" de la carrera Licenciatura en Sistemas,
    Universidad Nacional de la Patagonia Austral (UNPA).
    
    Esquema XSD para validación de géneros musicales.
    Realizado como parte del trabajo práctico 02, ejercicio 02.

    Autor: Nicolás Butterfield
    Año: 2025
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="generos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="genero" type="generoType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="idUnico">
      <xs:selector xpath="genero"/>
      <xs:field xpath="id"/>
    </xs:unique>
  </xs:element>

  <xs:complexType name="generoType">
    <xs:sequence>
      <xs:element name="id" type="xs:positiveInteger"/>
      <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== NicoButter/ldp_tp2_2025/EJERCICIO_02/generos/BUTTERFIELD_TP02_E02_GENEROS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Ejercicio de la materia "Laboratorio de Programación" de la carrera Licenciatura en Sistemas,
    Universidad Nacional de la Patagonia Austral (UNPA).
    
    Archivo XML de géneros musicales.
    Realizado como parte del trabajo práctico 02, ejercicio 02,

    Autor: Nicolás Butterfield
    Año: 2025
-->
<generos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BUTTERFIELD_TP02_E02_GENEROS.xsd">
    <genero>
        <id>101</id>
        <nombre>Rock</nombre>
    </genero>
    <genero>
        <id>102</id>
        <nombre>Rock Nacional</nombre>
    </genero>
    <genero>
        <id>103</id>
        <nombre>Pop</nombre>
    </genero>
</generos>
